- name: make sure packages are installed
  package:
    name: fzf
    state: present
  become: yes

- name: download iosevka-term font
  git:
    repo: https://aur.archlinux.org/ttf-iosevka-term.git
    dest: ~/workspace/ttf-iosevka-term

- name: check if iosevka-term font was downloaded
  stat:
    path: ~/workspace/ttf-iosevka-term
  register: iosevka

- name: install iosevka-term font
  command: makepkg -si --noconfirm
  args:
    chdir: ~/workspace/ttf-iosevka-term
  when: iosevka.stat.exists
